version: '2'
services:
    usersapi-app:
        image: usersapi
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://usersapi-postgresql:5432/usersapi
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    usersapi-postgresql:
        extends:
            file: postgresql.yml
            service: usersapi-postgresql
