version: '2'
services:
    usersapi-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/usersapi/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=usersapi
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
